### PR TITLE
Sistema interno SISCON

### PR DESCRIPTION
**Pull request by MarcioPaulo**

### CODE REVIEW

**Comment by MarcioPaulo** [comment]
@ArtemAvramenko 

Hello ArtemAvramenko, 
It is totally private.

**Comment by MarcioPaulo** [comment]
@ArtemAvramenko 

my tests

tmetricsiscon2
tmetricsiscon3

**Comment by ArtemAvramenko** [comment]
Sorry, but we cannot include private system integration to TMetric.

**Comment by MarcioPaulo** [comment]
oks

**Pull request closed without merging**
